### PR TITLE
Add support for Post Device Update

### PR DESCRIPTION
**Pull request by nithinyell**
Ready for review.

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@lucholaf hello! when you have a moment, can you please review this PR?

**Comment by attsdk** [comment]
@kristinpeterson This PR is still pending.

**Comment by nithinyell** [comment]
Updated as directed. Please review.

**Comment by lucholaf** [comment]
@nithinyell was main .storyboard deleted on https://github.com/attm2x/m2x-ios/commit/2011e5a ?

**Comment by nithinyell** [comment]
@lucholaf  That storyboard has got unnecessary changes while updating feature.

**Comment by lucholaf** [comment]
@nithinyell but now looks like the whole file content is deleted in this PR

**Comment by nithinyell** [comment]
@lucholaf Please review the changes

**Pull request merged**
